<?php $this->headScript()->captureStart() ?>
  AC_FL_RunContent = 0;
<?php $this->headScript()->captureEnd() ?>
<?php $this->headScript()->appendFile('/js/AC_RunActiveContent.js');
?>
  <script type="text/javascript">
    if (AC_FL_RunContent == 0) {
            alert("This page requires AC_RunActiveContent.js.");
    } else {
            AC_FL_RunContent(
                    'codebase', 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0',
                    'width', '460',
                    'height', '370',
                    'src', '/media/flash/videoplayer',
                    'quality', 'high',
                    'FlashVars', 'video=<?php print "$this->video"; ?>&desc="test"',
                    'pluginspage', 'http://www.macromedia.com/go/getflashplayer',
                    'align', 'middle',
                    'play', 'true',
                    'loop', 'true',
                    'scale', 'showall',
                    'wmode', 'window',
                    'devicefont', 'false',
                    'id', '/media/flash/videoplayer',
                    'bgcolor', '#000000',
                    'name', '/media/flash/videoplayer',
                    'menu', 'true',
                    'allowFullScreen', 'true',
                    'allowScriptAccess','sameDomain',
                    'movie', '/media/flash/videoplayer',
                    'salign', ''
                    ); //end AC code
    }
</script>
<noscript>
        <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="440" height="365" id="/media/flash/videoplayer" align="middle">
        <param name="allowScriptAccess" value="sameDomain" />
        <param name="allowFullScreen" value="false" />
        <param name="movie" value="/media/flash/videoplayer.prt2.swf" />
        <param name="quality" value="high" />
        <param name="bgcolor" value="#000000" />
        <param name="FlashVars" value="itemID=<?php print "$this->video"; ?>">

        <embed src="/media/flash/videoplayer.swf" FlashVars="itemID=<?php print "$this->video"; ?>" quality="high" bgcolor="#000000" width="440" height="365" name="/media/flash/videoplayer" align="middle" allowScriptAccess="sameDomain" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
        </object>
</noscript>


