<?php
/* @var $this Zend_View */
?>
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">

    <head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>
        <base href="/" />
    </head>

    <body>
        <div id="wrapper">
            <div id="header">
                <div id="logo">
                    <a href="/">ZF<span>1.10.6</span></a>
                </div>
            </div>
            <div id="content">
                <div id="left">
                    <div id="nav">
                        <? echo $this->action('nav', 'menus', null, array('menu' => 'main')); ?>
                        <?php echo $this->navigation()->menu(); ?>
                    </div>
                </div>
                <div id="right">
			<?= $this->layout()->content ?>
                </div>
            </div>
            <div id="footer">
                <span id="copy"><a id="admin" href="/admin" target="_blank"> &copy;</a> 2010 BN Technology Group - All Rights Reserved</span>
            </div>
        </div>
    </body>

</html>