<h1><?= $this->model->title;?></h1>
<?= $this->model->body; ?>

<table cellspacing="0">

<?php foreach ($this->jobs as $jobs): ?>
    <tr>
        <td><h3><a href="/careers/view/job/<?= $jobs->job_id; ?>" > <?php echo str_replace('_', ' ', $jobs->title); ?> </a> </h3></td>
        <td><?=$jobs->created; ?></td>
   </tr>
   <tr>
       <td colspan="2" ><?=$jobs->intro; ?></td>
   </tr>
<?php endforeach; ?>

</table>
