<?php $this->headScript()->appendFile('/js/ckeditor/ckeditor.js'); ?>


<?= $this->message; ?>

<p>Date: <?= $this->contact->created; ?></p>
<p>From: <?= $this->contact->name; ?></p>
<p>Email: <?= $this->contact->email; ?></p>
<p>Comments: <?= $this->contact->comments; ?></p>

<?= $this->form; ?>


<script type="text/javascript">
    CKEDITOR.replace(('body'),{

        width: "70%"

    });
</script>